#!/bin/sh

# Usage:
# `$0`: Ask for recording type via dmenu
# `$0 screencast`: Record both audio and screen
# `$0 video`: Record only screen
# `$0 audio`: Record only audio
# `$0 kill`: Kill existing recording
#
# If there is already a running instance, user will be prompted to end it.


killrecording() {
	recpid="$(cat /tmp/recordingpid)"
	# kill with SIGTERM, allowing finishing touches.
	kill -15 "$recpid"
	rm -f /tmp/recordingpid
	pkill -RTMIN+9 "${STATUSBAR:-dwmblocks}"
	# even after SIGTERM, ffmpeg may still run, so SIGKILL it.
	sleep 3
	kill -9 "$recpid"
	exit
	}

videoselected() {
	output="$HOME/video-$(date '+%y%m%d-%H%M-%S').mkv" &
	slop -f "%x %y %w %h" > /tmp/slop
	read -r X Y W H < /tmp/slop
	rm /tmp/slop

	LIBVA_DRIVER_NAME=i965 \
	ffmpeg \
	-vaapi_device /dev/dri/renderD128 \
	-f x11grab \
	-video_size "$W"x"$H" \
	-i :0.0+"$X,$Y" \
	-f alsa \
	-i default \
	-vf 'format=nv12,hwupload' \
	-c:v h264_vaapi -f mp4 -rc_mode 1 \
 	-qp 25 -r 60 \
	$output &
	echo $! > /tmp/recordingpid
	dunstify "video saved to $output"
	}	
video(){
	output="$HOME/video-$(date '+%y%m%d-%H%M-%S').mkv"
	LIBVA_DRIVER_NAME=i965 \
	ffmpeg \
	-vaapi_device /dev/dri/renderD128 \
	-f x11grab \
	-i "$DISPLAY" \
	-f alsa \
	-i default \
	-vf 'format=nv12,hwupload' \
	-c:v h264_vaapi -f mp4 -rc_mode 1 \
 	-qp 25 -r 60 \
	$output &
	echo $! > /tmp/recordingpid
	dunstify "video saved to $output"
	}


audio() { \
	ffmpeg \
	-f alsa -i default \
	-c:a flac \
	"$HOME/audio-$(date '+%y%m%d-%H%M-%S').flac" &
	echo $! > /tmp/recordingpid
	}

screenshotselected() {
	output="$HOME/screenshots-$(date '+%y%m%d-%H%M-%S').png"
	slop -f "%x %y %w %h" > /tmp/slop || exit
	read -r X Y W H < /tmp/slop
	rm /tmp/slop

	ffmpeg \
	-f x11grab \
	-video_size "$W"x"$H" \
	-i :0.0+"$X,$Y" \
	-f alsa \
	-i default \
	-vframes 1 \
	$output &
	dunstify "screenshot saved to $output"
	}	
screenshot() {
	output="$HOME/screenshots-$(date '+%y%m%d-%H%M-%S').png"
	ffmpeg \
	-f x11grab \
	-i "$DISPLAY" \
	-f alsa \
	-i default \
	-vframes 1 \
	$output &
	dunstify "screenshot saved to $output"
	}	


askrecording() { \
	choice=$(printf "screenshot\\nscreenshot selected\\nvideo\\nvideo selected\\naudio" | dmenu -i -p "Select recording style:")
	case "$choice" in
		screenshot) screenshot;;
		"screenshot selected") screenshotselected;;
		audio) audio;;
		video) video;;
		"video selected") videoselected;;
	esac
	}

asktoend() { \
	response=$(printf "No\\nYes" | dmenu -i -p "Recording still active. End recording?") &&
	[ "$response" = "Yes" ] &&  killrecording
	}


case "$1" in
	"screenshot selected") screenshotselected;;
	audio) audio;;
	video) video;;
	"video selected") videoselected;;
	kill) killrecording;;
	*) ([ -f /tmp/recordingpid ] && asktoend && exit) || askrecording;;
esac
